<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SPCOKLAP-5140" failures="1" tests="15" name="Default test" time="2578.791" errors="0" timestamp="2025-01-21T21:31:48 IST">
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Login_to_call_centre_application_and_take_account_filtration_pages" time="56.212"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Select_SMA_and_NPA_Categorie" time="12.783"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="SMA_Category_Selections" time="3.553"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="NPA_Category_Selections" time="4.176"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Allocation_Type_Selections__Auto" time="4.237"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Allocated_To_Selection__Call_Centre" time="3.604"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Perform_Search_with_Valid_Datas" time="10.529"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Verify_Total_Account_and_Amount_in_Grid" time="3.065"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Download_File__List_of_Accounts" time="7.029"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Verify_Downloaded_File" time="3.234"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Download_Dialer_File" time="7.498"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Verify_Dialer_Downloaded_File" time="0.087">
    <failure type="java.lang.AssertionError" message="Accounts do not match those indicated in the grid. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Accounts do not match those indicated in the grid. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule.Verify_Dialer_Downloaded_File(AllScenarios_CoreAutoAllocationModule.java:805)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Verify_Dialer_Downloaded_File -->
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Download_Invalid_MobileNo_Excel_File" time="8.08"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Verify_Invalid_Mobile_Number_Downloaded_File" time="3.066"/>
  <testcase classname="com.test.CoreAutoAllocation_Module.AllScenarios_CoreAutoAllocationModule" name="Verify_Download_History" time="2449.886"/>
</testsuite> <!-- Default test -->
